# Generated by Django 2.2.3 on 2019-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edamam_service', '0002_auto_20190712_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.TextField()),
                ('ingredient_count', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('url', models.TextField(db_index=True)),
                ('recipes', models.ManyToManyField(related_name='foods', to='edamam_service.Food')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
